INSERT INTO "agronomists" (first_name,last_name) 
VALUES 
('Brandon','Bullock'),
('Selma','Snider'),
('Kyra','Holder'),
('Heather','Ramsey'),
('Marvin','Schneider'),
('Mary','Morales'),
('Robin','Kirby'),
('Savannah','Baldwin'),
('Ivor','Holden'),
('Kennan','Swanson'),
('Lara','Roberts'),
('Natalie','Rojas'),
('Tallulah','Petersen'),
('Yetta','Lancaster'),
('Alexa','Henry'),
('Sylvester','Stark'),
('Bo','Coffey'),
('Burton','Long'),
('Lacey','Gregory'),
('Montana','Vargas'),
('Brenna','George'),
('Raphael','Schwartz'),
('Flynn','Cote'),
('Bell','Shannon'),
('Dale','Duncan'),
('Joel','Franks'),
('Mannix','Welch'),
('Owen','Cunningham'),
('Rylee','Coffey'),
('Kim','Miller');

INSERT INTO "customers" (first_name,last_name)
VALUES
('Rama','Sweeney'),
('Benedict','Delaney'),
('Hilda','Good'),
('Christian','Middleton'),
('Cora','Mcfarland'),
('Colby','Walsh'),
('Harlan','Leonard'),
('Fay','Cannon'),
('Adrian','Joseph'),
('Emily','Barry'),
('Tad','Dorsey'),
('Ronan','Fields'),
('Shelley','Mills'),
('Ivan','William'),
('Jane','Levine'),
('Rosalyn','Peters'),
('Libby','Barlow'),
('Jerome','Yates'),
('Caldwell','Mcconnell'),
('Wang','Kemp'),
('Ivor','Bush'),
('Dakota','Callahan'),
('Quin','Snow'),
('Chaney','Gilmore'),
('Kennan','Case'),
('Jonas','Sosa'),
('Ebony','Randolph'),
('Bethany','Calhoun'),
('Erica','Booker'),
('Cleo','Joyner');


INSERT INTO hemp_sort (sort_name)
VALUES ('Tibey-amarillo'),
('Western Snow Lichen'),
('Thickstem Wild Cabbage'),
('Metamelaena Lichen'),
('Western Giant Hyssop'),
('Fendler''s Meadow-rue'),
('Beet'),
('Red Monardella'),
('Dwarf Crabgrass'),
('Black Disc Lichen'),
('Slender Threeseed Mercury'),
('Apalachicola False Rosemary'),
('Texas Pricklyleaf'),
('Calamus'),
('Evergreen Sumac'),
('Maguire''s Milkvetch'),
('Spreading Eryngo'),
('Mountain Heather'),
('Hammock Velvetseed'),
('Crossidium Moss');